name: MLOps

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions: write-all

jobs:
  setup-runner:
    runs-on: [self-hosted, base-runner]
    if: github.event_name == 'pull_request'
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl for Amazon EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.EKS_CLUSTER_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Initialize specialized runner on Kubernetes
        run: |
          export GITHUB_RUN_ID="${{ github.run_id }}"
          envsubst < kubernetes/runner-gpu.yaml | kubectl apply -f -

  train-and-report:
    needs: setup-runner
    runs-on: [self-hosted, gpu-runner]
    if: github.event_name == 'pull_request'
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Train model
        run: dvc repro --pull

      - name: Push the outcomes to DVC remote storage
        run: dvc push

      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Commit changes in dvc.lock
          file_pattern: dvc.lock

      - name: Setup CML
        uses: iterative/setup-cml@v2
        with:
          version: '0.20.6'
          vega: false

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --depth=1 origin main:main

          echo "# Experiment Report (${{ github.sha }})" >> report.md

          echo "## Params workflow vs. main" >> report.md
          dvc params diff main --md >> report.md

          echo "## Metrics workflow vs. main" >> report.md
          dvc metrics diff main --md >> report.md

          dvc plots diff main

          echo "## Plots" >> report.md

          echo "### Training History" >> report.md
          echo "#### main" >> report.md
          echo '![](./dvc_plots/static/main_evaluation_plots_training_history.png "Training History")' >> report.md
          echo "#### workspace" >> report.md
          echo '![](./dvc_plots/static/workspace_evaluation_plots_training_history.png "Training History")' >> report.md

          echo "### Predictions Preview" >> report.md
          echo "#### main" >> report.md
          echo '![](./dvc_plots/static/main_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md
          echo "#### workspace" >> report.md
          echo '![](./dvc_plots/static/workspace_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md

          echo "### Confusion Matrix" >> report.md
          echo "#### main" >> report.md
          echo '![](./dvc_plots/static/main_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md
          echo "#### workspace" >> report.md
          echo '![](./dvc_plots/static/workspace_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md

          cml comment update --target=pr --publish report.md

  cleanup-runner:
    needs: train-and-report
    runs-on: [self-hosted, base-runner]
    if: github.event_name == 'pull_request' && (success() || failure() || cancelled())
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl for Amazon EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.EKS_CLUSTER_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Cleanup specialized runner on Kubernetes
        run: |
          export GITHUB_RUN_ID="${{ github.run_id }}"
          envsubst < kubernetes/runner-gpu.yaml | kubectl delete --wait=false -f -

  publish-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check model
        run: dvc repro --pull

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Import the BentoML model
        run: bentoml models import model/celestial_bodies_classifier_model.bentomodel

      - name: Build the BentoML model artifact
        run: bentoml build src

      - name: Containerize the BentoML model artifact Docker image
        run: |
          bentoml containerize celestial_bodies_classifier:latest \
            --image-tag ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest \
            --image-tag ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Configure kubectl for Amazon EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.EKS_CLUSTER_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Update Kubernetes deployment image
        run: |
          sed -i "s|image: .*celestial-bodies-classifier:.*|image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}|g" kubernetes/deployment.yaml

      - name: Deploy model to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
